# These are supported funding model platforms

github: blakmatrix
patreon: sudomeditate
open_collective: vitepress-jsdoc
ko_fi: blakmatrix
tidelift: npm/vitepress-jsdoc
liberapay: blakmatrix
issuehunt: blakmatrix

